# Generated by Django 3.2.5 on 2022-02-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100)),
                ('taskDescription', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('status', models.CharField(choices=[('New', 'New'), ('Started', 'Started'), ('Ongoing', 'Ongoing'), ('In QA', 'In QA'), ('Completed', 'Completed')], default='New', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100)),
                ('taskDescription', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('status', models.CharField(choices=[('New', 'New'), ('Started', 'Started'), ('Ongoing', 'Ongoing'), ('In QA', 'In QA'), ('Completed', 'Completed')], default='New', max_length=50)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.task')),
            ],
        ),
    ]
